// import { useSession } from "next-auth/react";

import Footer from "../../components/layout/Footer";
import Header from "../../components/layout/Header";

// import { useRouter } from "next/navigation";
export const metadata = {
  title: "About",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Header />
      <div className="mt-5 m-0 p-0 pt-5">{children}</div>
      {/* <Footer /> */}
    </>
  );
}
