import "/node_modules/bootstrap/dist/css/bootstrap.min.css";
import "../assets/font/stylesheet.css";
import "/node_modules/bootstrap/dist/css/bootstrap.min.css";
import { Inter } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import ProgressBar from "../components/Dashboard/ProgressBar";
import Authprovider from "../components/Authprovider";
import Contextprovider from "../context/Contextprovider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  try {
    return (
      <html lang="en">
        <head>
          <link
            rel="preload"
            href="https://kit.fontawesome.com/fad44c7e6b.js"
            as="script"
            crossOrigin="anonymous"
          ></link>
          <script
            src="https://kit.fontawesome.com/fad44c7e6b.js"
            crossOrigin="anonymous"
          ></script>
          <script
            src="https://cdn.jsdelivr.net/npm/react/umd/react.production.min.js"
            crossOrigin="anonymous"
          ></script>
          <script
            rel="preload"
            src="https://cdn.jsdelivr.net/npm/react/umd/react.production.min.js"
            crossOrigin="anonymous"
          />
          <script
            src="https://cdn.jsdelivr.net/npm/react-dom/umd/react-dom.production.min.js"
            crossOrigin="anonymous"
          ></script>
          <script
            rel="preload"
            src="https://cdn.jsdelivr.net/npm/react-bootstrap@next/dist/react-bootstrap.min.js"
            crossOrigin="anonymous"
          />
          <script
            src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
            crossOrigin="anonymous"
          ></script>
          <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
            crossOrigin="anonymous"
          ></script>
        </head>
        <body className={inter.className} suppressHydrationWarning={true}>
          {/* <Contextprovider> */}
          <Authprovider>
            <>
              <div className="">{children}</div>
            </>
          </Authprovider>
          {/* </Contextprovider> */}
        </body>
      </html>
    );
  } catch (error: any) {
    resolve(error);
  }
}
function resolve(error: any) {
  throw new Error("Function not implemented.");
}
